#!/bin/bash

param=$1
var2="start"
date=$( TZ=America/Los_Angeles date +'%Y-%m-%d_%H:%M' )
printf "$date "

# Exit script if no/wrong params are given
if [[ ( -z $param ) || ( ! $param =~ ^(start|stop|restart|status|update)$ ) ]]; then
  printf "Correct usage: ./server start|stop|restart|status|update\n"
  exit 1
fi

function outputCountdown() {
  seconds=$1
  range=$( eval echo {$seconds..1} )
  for i in $range; do
    printf "$i.."
    sleep 1
  done
}

function isServerRunning() {
  # Get processes running from current Ubuntu user and counts any process
  # matching the word "Insurgency"
  numServerInstance=$( ps -u $USER | grep -c Insurgency )

  if [[ $numServerInstance > 0 ]]; then
    return 0
  else
    return 1
  fi
}

function prompt() {
  question=$1

  while true; do
    read -p "$question Proceed? " yn
    case $yn in
      [Yy]*) break;;
      [Nn]*) exit;;
      *) printf "Please answer yes or no. ";;
    esac
  done
}

function forceStop() {
  printf "Failed..Force stopping in.."

  killall InsurgencyServer-Linux-Shipping
  outputCountdown 2

  if $( isServerRunning ); then
    printf "Failed..Process is still running.\n"
  else
    printf "Force stopped.\n"
  fi

  exit
}

function stop() {
  quiet=$1

  # Simulate a ctrl+c command
  screen -X -S "Sand1" stuff "^C"
  outputCountdown 4

  if $( isServerRunning ); then
    forceStop
  else
    [[ -z $quiet ]] && printf "Stopped.\n"
  fi
}

function handleStop() {
  $( ! isServerRunning ) && { printf "Server is not running.\n"; exit; }

  # stop "$1"
  quiet=$1

  # Simulate a ctrl+c command
  screen -X -S "Sand1" stuff "^C"
  outputCountdown 4

  if $( isServerRunning ); then
    forceStop
  else
    [[ -z $quiet ]] && printf "Stopped.\n"
  fi
}

function handleStart() {
  quiet=$1

  if $( isServerRunning ); then
    printf "Server is already running.\n"
  else
    #copyConfigScripts
    $HOME/scripts/$var2
    [[ -z $quiet ]] && printf "Started.\n"
  fi
}

function handleRestart() {
  handleStop "quietly"
  handleStart "quietly"
  printf "Restarted!\n"
}

function handleStatus() {
  if $( isServerRunning ); then
    echo "Online"
  else
    echo "Offline"
  fi
}

function handleUpdate() {
  prompt "Have you installed Steam already?"
  /home/ins/Steam/steamcmd.sh +login anonymous +force_install_dir /home/ins/iss +app_update 581330 validate +quit
}

# Begin program
case $param in
  status)
    handleStatus
    exit
    ;;
  stop)
    handleStop
    exit
    ;;
  start)
    handleStart
    exit
    ;;
  restart)
    handleRestart
    exit
    ;;
  forceRestart)
    handleRestart
    exit
    ;;
  update)
    handleUpdate
    exit
    ;;
esac
