#!/bin/bash
screen -S Sand1 -d -m /home/steam/sandstorm/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Precinct?Scenario=Scenario_Precinct_Checkpoint_Security?MaxPlayers=10?password=putpasswordhere -Port=7777 -QueryPort=27015 -mutators=Vampirism -log -LogCmds="LogGameplayEvents Log" -hostname="insTactical.com - Slow / No Rushing - - - - - - - - - - - - - - - - - -"
