#!/bin/bash

#date=$( TZ=America/Los_Angeles date +'%Y-%m-%d_%H:%M' )
#echo $date: Server restarted >> /home/ins/restarts.log

# Kill server process
killall InsurgencyServer-Linux-Shipping
#sleep 5

# Start server
#/home/ins/server start > /dev/null 2>&1
