#!/bin/bash
# Randomized array credit: https://github.com/schroeder-lvb

array[0]="?Scenario=Scenario_Crossing_Checkpoint_Security"
array[1]="?Scenario=Scenario_Farmhouse_Checkpoint_Security"
array[2]="?Scenario=Scenario_Summit_Checkpoint_Security"
array[3]="?Scenario=Scenario_Refinery_Checkpoint_Security"
array[4]="?Scenario=Scenario_Precinct_Checkpoint_Security"
array[5]="?Scenario=Scenario_Hideout_Checkpoint_Security"
array[6]="?Scenario=Scenario_Ministry_Checkpoint_Security"
array[7]="?Scenario=Scenario_Hillside_Checkpoint_Security"
array[8]="?Scenario=Scenario_Outskirts_Checkpoint_Security"
array[9]="?Scenario=Scenario_PowerPlant_Checkpoint_Security"
array[10]="?Scenario=Scenario_Tideway_Checkpoint_Security"
array[11]="?Scenario=Scenario_Bab_Checkpoint_Security"
array[12]="?Scenario=Scenario_Citadel_Checkpoint_Security"
array[13]="?Scenario=Scenario_Gap_Checkpoint_Security"

size=${#array[@]}
index=$(($RANDOM % $size))
#echo ${array[$index]}

# Private
# screen -S Sand1 -d -m /home/ins/iss/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Ministry?Scenario=Scenario_Ministry_Checkpoint_Security?MaxPlayers=6?Password=secret -Port=7777 -QueryPort=27015 -log -LogCmds="LogGameplayEvents Log" -motd -hostname="aaaa aaaa" -EnableCheats -noeac

# Public
#screen -S Sand1 -d -m /home/ins/iss/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping ${array[$index]}?MaxPlayers=6 -Port=7777 -QueryPort=27015 -GameStats -GSLTToken=secret -log -LogCmds="LogGameplayEvents Log" -motd -hostname="info.insTactical.com - Slow" -noeac
screen -S Sand1 -d -m /home/ins/iss/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Town?Scenario=Scenario_Hideout_Checkpoint_Security?MaxPlayers=6 -Port=7777 -QueryPort=27015 -GameStats -GSLTToken=secret -log -LogCmds="LogGameplayEvents Log" -motd -hostname="info.insTactical.com - Slow" -noeac