#!/bin/bash

# Remove comments (Steam alias)
grep -o '^[^#]*' /home/ins/scripts/Admins-labels.txt > /home/ins/scripts/sandstorm/Admins.txt
sleep 1

cp /home/ins/scripts/sandstorm/Game.ini /home/ins/iss/Insurgency/Saved/Config/LinuxServer/Game.ini
cp /home/ins/scripts/sandstorm/Engine.ini /home/ins/iss/Insurgency/Saved/Config/LinuxServer/Engine.ini
cp /home/ins/scripts/sandstorm/Admins.txt /home/ins/iss/Insurgency/Config/Server/Admins.txt
cp /home/ins/scripts/sandstorm/Motd.txt /home/ins/iss/Insurgency/Config/Server/Motd.txt
cp /home/ins/scripts/sandstorm/MapCycle.txt /home/ins/iss/Insurgency/Config/Server/MapCycle.txt

sleep 1

# Randomized array credit: https://github.com/schroeder-lvb
array[0]="Canyon?Scenario=Scenario_Crossing_Checkpoint_Security"
array[1]="Farmhouse?Scenario=Scenario_Farmhouse_Checkpoint_Security"
array[2]="Mountain?Scenario=Scenario_Summit_Checkpoint_Security"
array[3]="Oilfield?Scenario=Scenario_Refinery_Checkpoint_Security"
array[4]="Precinct?Scenario=Scenario_Precinct_Checkpoint_Security"
array[5]="Town?Scenario=Scenario_Hideout_Checkpoint_Security"
array[6]="Ministry?Scenario=Scenario_Ministry_Checkpoint_Security"
array[7]="Sinjar?Scenario=Scenario_Hillside_Checkpoint_Security"
array[8]="Compound?Scenario=Scenario_Outskirts_Checkpoint_Security"
array[9]="PowerPlant?Scenario=Scenario_PowerPlant_Checkpoint_Security"
array[10]="Buhriz?Scenario=Scenario_Tideway_Checkpoint_Security"
array[11]="Bab?Scenario=Scenario_Bab_Checkpoint_Security"
array[12]="Citadel?Scenario=Scenario_Citadel_Checkpoint_Security"
array[13]="Gap?Scenario=Scenario_Gap_Checkpoint_Security"

size=${#array[@]}
index=$(($RANDOM % $size))
#echo ${array[$index]}

# Private
# screen -S Sand1 -d -m /home/ins/iss/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Ministry?Scenario=Scenario_Ministry_Checkpoint_Security?MaxPlayers=6?Password=secret -Port=7777 -QueryPort=27015 -log -LogCmds="LogGameplayEvents Log" -motd -hostname="aaaa aaaa" -EnableCheats -noeac

# Public
#screen -S Sand1 -d -m /home/ins/iss/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping ${array[$index]}?MaxPlayers=6 -Port=7777 -QueryPort=27015 -GameStats -GSLTToken=secret -log -LogCmds="LogGameplayEvents Log" -motd -hostname="info.insTactical.com - Slow" -noeac
#screen -S Sand1 -d -m /home/ins/iss/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Town?Scenario=Scenario_Hideout_Checkpoint_Security?MaxPlayers=8 -Port=7777 -QueryPort=27015 -GameStats -GSLTToken=secret -log -LogCmds="LogGameplayEvents Log" -motd -hostname="info.insTactical.com - Slow" -noeac
screen -S Sand1 -d -m /home/ins/iss/Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping ${array[$index]}?Game=CheckpointHardcore?MaxPlayers=6?Mutators=MapVoteLabels,Medic -Mods -ModList=Mods.txt -ModDownloadTravelTo=${array[$index]}?Game=CheckpointHardcore -Port=7777 -QueryPort=27015 -GameStatsToken=secret -GameStats -GSLTToken=secret -log -LogCmds="LogGameplayEvents Log" -motd -hostname="YOUR HOSTNAME GOES HERE" -noeac
